grid:
  postprocess_type:
    - GREEDYNMM
    - NMM
  match_metric:
    - IOU
    - IOS
  match_threshold:
    - 0.4
    - 0.5
    - 0.6
    - 0.7
    - 0.8
    - 0.9
  conf:
    - 0.05
    - 0.10
    - 0.15
    - 0.20
    - 0.25
    - 0.30
    - 0.35
  mask_threshold:
    - 0.4
    - 0.5
    - 0.6